// Generated by scripts/make-thumbs.mjs — do not edit by hand.
// Covers that have a 500 × 600 WebP in public/photos/thumbs/.
export const THUMBNAILED = new Set<string>([
  "IMG-20251128-WA0019.png",
  "IMG-20251130-WA0019.png",
  "IMG-20251130-WA0022.png",
  "IMG-20251130-WA0023.png",
  "IMG-20251202-WA0037.png",
  "IMG-20260206-WA0062.png",
  "IMG-20260213-WA0054.png",
  "IMG-20260310-WA0017.png",
  "IMG-20260808-WA0045.png",
  "IMG-20260808-WA0046.png",
  "IMG-20260913-WA0002.png",
  "IMG-20260913-WA0003.png",
  "IMG-20260913-WA0005.png",
  "IMG-20260913-WA0006.png",
  "IMG-20260913-WA0007.png",
  "IMG-20260913-WA0008.png",
  "IMG-20260913-WA0009.png",
  "IMG-20260913-WA0011.png",
  "IMG-20260913-WA0012.png",
  "IMG-20260913-WA0013.png",
  "IMG-20260913-WA0014.png"
]);
