-- ============================================================================
--  Bakesbymom — Cake Catalog schema for Cloudflare D1 (SQLite)
-- ============================================================================
--  HOW TO RUN
--    npx wrangler d1 execute bakesbymom --remote --file=./db/schema.sql
--  (drop --remote to seed the local dev database instead)
--
--  It is safe to run more than once (IF NOT EXISTS everywhere, and the seed
--  block only inserts when the catalog is still empty).
--
--  WHAT IT CREATES
--  - Tables: categories, cakes, cake_photos, cake_flavours, cake_addons
--  - Indexes for the foreign-key lookups the app does constantly
--
--  ACCESS CONTROL
--  D1 has no row-level security: the database is reachable only through the
--  Worker in worker/index.ts, which is the single gatekeeper. Reads are public;
--  every write requires the x-admin-password header to match the worker's
--  ADMIN_PASSWORD secret. See the note at the bottom of this file.
--
--  Primary keys are UUID text columns generated by the Worker
--  (crypto.randomUUID()), so there is no server-side default here.
-- ============================================================================

-- A category groups cakes together, e.g. "Birthday", "Wedding", "Cupcakes".
create table if not exists categories (
  id          text primary key,
  name        text not null,
  description text,
  image_url   text,
  sort_order  integer not null default 0,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- A single cake within a category.
create table if not exists cakes (
  id              text primary key,
  category_id     text not null references categories (id) on delete cascade,
  name            text not null,
  description     text,
  -- price per pound (informational, shown on the detail page)
  per_pound_price real not null default 0,
  -- default / reference weight in kilograms
  weight_kg       real not null default 0,
  -- the base ("fixed") price the final price is built on top of
  fixed_price     real not null default 0,
  sort_order      integer not null default 0,
  created_at      text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Photos for a cake (a cake can have many). `url` points at the Worker's
-- /api/photos/<key> route, which streams the object out of R2.
create table if not exists cake_photos (
  id         text primary key,
  cake_id    text not null references cakes (id) on delete cascade,
  url        text not null,
  sort_order integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Flavour options for a cake — used to populate the dropdown on the detail page.
-- price_delta lets a flavour optionally add to the price (0 = no extra charge).
create table if not exists cake_flavours (
  id          text primary key,
  cake_id     text not null references cakes (id) on delete cascade,
  name        text not null,
  price_delta real not null default 0,
  sort_order  integer not null default 0,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Customization add-ons for a cake (e.g. "Extra tier", "Fresh flowers").
-- Selecting these adds price_delta to the final price.
create table if not exists cake_addons (
  id          text primary key,
  cake_id     text not null references cakes (id) on delete cascade,
  name        text not null,
  price_delta real not null default 0,
  sort_order  integer not null default 0,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create index if not exists idx_cakes_category on cakes (category_id);
create index if not exists idx_photos_cake    on cake_photos (cake_id);
create index if not exists idx_flavours_cake  on cake_flavours (cake_id);
create index if not exists idx_addons_cake    on cake_addons (cake_id);

-- ---------------------------------------------------------------------------
--  OPTIONAL — seed a couple of rows so the catalog isn't empty on first load.
--  Delete this block if you'd rather start from scratch in the admin panel.
--  The `where not exists` guard keeps re-runs from duplicating the seed.
-- ---------------------------------------------------------------------------
insert into categories (id, name, description, sort_order)
select 'seed-cat-birthday', 'Birthday Cakes',
       'Celebration cakes for every kind of birthday.', 1
where not exists (select 1 from categories);

insert into cakes (id, category_id, name, description, per_pound_price, weight_kg, fixed_price, sort_order)
select 'seed-cake-choco', 'seed-cat-birthday', 'Classic Chocolate Truffle',
       'Rich chocolate sponge layered with silky truffle ganache.',
       450.00, 1.0, 600.00, 1
where exists (select 1 from categories where id = 'seed-cat-birthday')
  and not exists (select 1 from cakes where id = 'seed-cake-choco');

insert into cake_flavours (id, cake_id, name, price_delta, sort_order)
select 'seed-flav-truffle', 'seed-cake-choco', 'Chocolate Truffle', 0, 1
where exists (select 1 from cakes where id = 'seed-cake-choco')
  and not exists (select 1 from cake_flavours where cake_id = 'seed-cake-choco');
insert into cake_flavours (id, cake_id, name, price_delta, sort_order)
select 'seed-flav-belgian', 'seed-cake-choco', 'Belgian Dark', 100, 2
where exists (select 1 from cakes where id = 'seed-cake-choco')
  and not exists (select 1 from cake_flavours where id = 'seed-flav-belgian');
insert into cake_flavours (id, cake_id, name, price_delta, sort_order)
select 'seed-flav-hazelnut', 'seed-cake-choco', 'Choco Hazelnut', 150, 3
where exists (select 1 from cakes where id = 'seed-cake-choco')
  and not exists (select 1 from cake_flavours where id = 'seed-flav-hazelnut');

insert into cake_addons (id, cake_id, name, price_delta, sort_order)
select 'seed-addon-eggless', 'seed-cake-choco', 'Eggless', 0, 1
where exists (select 1 from cakes where id = 'seed-cake-choco')
  and not exists (select 1 from cake_addons where cake_id = 'seed-cake-choco');
insert into cake_addons (id, cake_id, name, price_delta, sort_order)
select 'seed-addon-flowers', 'seed-cake-choco', 'Fresh flowers on top', 250, 2
where exists (select 1 from cakes where id = 'seed-cake-choco')
  and not exists (select 1 from cake_addons where id = 'seed-addon-flowers');
insert into cake_addons (id, cake_id, name, price_delta, sort_order)
select 'seed-addon-plaque', 'seed-cake-choco', 'Custom message plaque', 120, 3
where exists (select 1 from cakes where id = 'seed-cake-choco')
  and not exists (select 1 from cake_addons where id = 'seed-addon-plaque');

-- ============================================================================
--  LOCKING DOWN WRITES
-- ============================================================================
--  Unlike Supabase there is no anon key that reaches the database directly —
--  the Worker is the only client, so the catalog cannot be written to without
--  the admin password. Set it once with:
--
--    npx wrangler secret put ADMIN_PASSWORD
--
--  If ADMIN_PASSWORD is unset the Worker refuses every write outright, so a
--  half-configured deployment fails closed rather than open.
-- ============================================================================
