/**
 * Builds the small WebP covers the Catalog shelves show.
 *
 * The photos in R2 are full-size phone PNGs — 0.4 to 2.3 MB each, ~26 MB for
 * the whole catalog — while a shelf tile is only 250 × 300 px. This pulls the
 * live catalog, takes each cake's cover (the restaged picture when there is
 * one, exactly as the site shows it), crops it to the tile's 5:6 shape at 2×
 * and writes it to public/photos/thumbs/. The list of covers that now have a
 * thumbnail goes to src/lib/thumbs.ts, which resolveThumbUrl() reads.
 *
 * Re-run after adding cakes in the Admin panel:
 *
 *   npm i --no-save sharp && node scripts/make-thumbs.mjs
 *
 * A cover without a thumbnail still works — the tile just falls back to the
 * full-size photo until this is run again. Existing thumbnails are kept, so
 * delete one from public/photos/thumbs/ to rebuild it (say, after a restage).
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const API = process.env.API_ORIGIN ?? "https://bakesbymom.snehagupta.workers.dev";
const OUT_DIR = path.join(ROOT, "public/photos/thumbs");
const MANIFEST = path.join(ROOT, "src/lib/thumbs.ts");

// The tile is 250 × 300; render at 2× for sharp text-free photos on retina.
const WIDTH = 500;
const HEIGHT = 600;

/** The restaged swaps live in api.ts; read them from there so they never drift. */
async function readRestaged() {
  const source = await readFile(path.join(ROOT, "src/lib/api.ts"), "utf8");
  const block = source.match(/RESTAGED_PHOTOS[^{]*\{([\s\S]*?)\};/)?.[1] ?? "";
  return Object.fromEntries(
    [...block.matchAll(/"([^"]+)":\s*"([^"]+)"/g)].map(([, key, local]) => [key, local]),
  );
}

const basename = (url) => url.slice(url.lastIndexOf("/") + 1);
const stem = (name) => name.replace(/\.[^.]+$/, "");

async function loadImage(url, restaged) {
  const local = restaged[basename(url)];
  if (local) return readFile(path.join(ROOT, "public", local));
  const absolute = /^https?:\/\//.test(url) ? url : `${API}${url.startsWith("/") ? "" : "/"}${url}`;
  const response = await fetch(absolute);
  if (!response.ok) throw new Error(`${response.status} for ${absolute}`);
  return Buffer.from(await response.arrayBuffer());
}

const restaged = await readRestaged();
const catalog = await (await fetch(`${API}/api/catalog`)).json();
const covers = catalog.flatMap((c) => c.cakes.map((cake) => cake.cover_url)).filter(Boolean);

await mkdir(OUT_DIR, { recursive: true });
const done = [];
for (const url of covers) {
  const name = basename(url);
  const out = path.join(OUT_DIR, `${stem(name)}.webp`);
  if (!existsSync(out)) {
    const input = await loadImage(url, restaged);
    await sharp(input)
      .rotate()
      .resize(WIDTH, HEIGHT, { fit: "cover", position: "centre" })
      .webp({ quality: 78 })
      .toFile(out);
  }
  done.push(name);
  console.log(`✓ ${name}`);
}

await writeFile(
  MANIFEST,
  `// Generated by scripts/make-thumbs.mjs — do not edit by hand.\n` +
    `// Covers that have a 500 × 600 WebP in public/photos/thumbs/.\n` +
    `export const THUMBNAILED = new Set<string>(${JSON.stringify(done.sort(), null, 2)});\n`,
);
console.log(`\n${done.length} thumbnails → public/photos/thumbs/`);
